// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NinginToolsExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "NinginToolsExtension.970705b7-70ba-4b14-857e-581237d43659";
        public const string Name = "NinginToolsExtension";
        public const string Description = @"NINGIN IS THE BESTNINGIN IS THE BESY";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
