namespace NinginCore
{
    public struct Colors
    {
        public static Color MediumAquamarine { get { return Color.FromRGBA(0x66, 0xCD, 0xAA, 0xFF); } }
        public static Color MediumBlue { get { return Color.FromRGBA(0x00, 0x00, 0xCD, 0xFF); } }
        public static Color MediumOrchid { get { return Color.FromRGBA(0xBA, 0x55, 0xD3, 0xFF); } }
        public static Color MediumPurple { get { return Color.FromRGBA(0x93, 0x70, 0xDB, 0xFF); } }
        public static Color MediumSeaGreen { get { return Color.FromRGBA(0x3C, 0xB3, 0x71, 0xFF); } }
        public static Color MediumSlateBlue { get { return Color.FromRGBA(0x7B, 0x68, 0xEE, 0xFF); } }
        public static Color MediumSpringGreen { get { return Color.FromRGBA(0x00, 0xFA, 0x9A, 0xFF); } }
        public static Color MediumTurquoise { get { return Color.FromRGBA(0x48, 0xD1, 0xCC, 0xFF); } }
        public static Color MediumVioletRed { get { return Color.FromRGBA(0xC7, 0x15, 0x85, 0xFF); } }
        public static Color MidnightBlue { get { return Color.FromRGBA(0x19, 0x19, 0x70, 0xFF); } }
        public static Color MintCream { get { return Color.FromRGBA(0xF5, 0xFF, 0xFA, 0xFF); } }
        public static Color MistyRose { get { return Color.FromRGBA(0xFF, 0xE4, 0xE1, 0xFF); } }
        public static Color Moccasin { get { return Color.FromRGBA(0xFF, 0xE4, 0xB5, 0xFF); } }
        public static Color NavajoWhite { get { return Color.FromRGBA(0xFF, 0xDE, 0xAD, 0xFF); } }
        public static Color Navy { get { return Color.FromRGBA(0x00, 0x00, 0x80, 0xFF); } }
        public static Color OldLace { get { return Color.FromRGBA(0xFD, 0xF5, 0xE6, 0xFF); } }
        public static Color Olive { get { return Color.FromRGBA(0x80, 0x80, 0x00, 0xFF); } }
        public static Color Maroon { get { return Color.FromRGBA(0x80, 0x00, 0x00, 0xFF); } }
        public static Color OliveDrab { get { return Color.FromRGBA(0x6B, 0x8E, 0x23, 0xFF); } }
        public static Color Magenta { get { return Color.FromRGBA(0xFF, 0x00, 0xFF, 0xFF); } }
        public static Color LimeGreen { get { return Color.FromRGBA(0x32, 0xCD, 0x32, 0xFF); } }
        public static Color LavenderBlush { get { return Color.FromRGBA(0xFF, 0xF0, 0xF5, 0xFF); } }
        public static Color LawnGreen { get { return Color.FromRGBA(0x7C, 0xFC, 0x00, 0xFF); } }
        public static Color LemonChiffon { get { return Color.FromRGBA(0xFF, 0xFA, 0xCD, 0xFF); } }
        public static Color LightBlue { get { return Color.FromRGBA(0xAD, 0xD8, 0xE6, 0xFF); } }
        public static Color LightCoral { get { return Color.FromRGBA(0xF0, 0x80, 0x80, 0xFF); } }
        public static Color LightCyan { get { return Color.FromRGBA(0xE0, 0xFF, 0xFF, 0xFF); } }
        public static Color LightGoldenrodYellow { get { return Color.FromRGBA(0xFA, 0xFA, 0xD2, 0xFF); } }
        public static Color LightGray { get { return Color.FromRGBA(0xD3, 0xD3, 0xD3, 0xFF); } }
        public static Color LightGreen { get { return Color.FromRGBA(0x90, 0xEE, 0x90, 0xFF); } }
        public static Color LightPink { get { return Color.FromRGBA(0xFF, 0xB6, 0xC1, 0xFF); } }
        public static Color LightSalmon { get { return Color.FromRGBA(0xFF, 0xA0, 0x7A, 0xFF); } }
        public static Color LightSeaGreen { get { return Color.FromRGBA(0x20, 0xB2, 0xAA, 0xFF); } }
        public static Color LightSkyBlue { get { return Color.FromRGBA(0x87, 0xCE, 0xFA, 0xFF); } }
        public static Color LightSlateGray { get { return Color.FromRGBA(0x77, 0x88, 0x99, 0xFF); } }
        public static Color LightSteelBlue { get { return Color.FromRGBA(0xB0, 0xC4, 0xDE, 0xFF); } }
        public static Color LightYellow { get { return Color.FromRGBA(0xFF, 0xFF, 0xE0, 0xFF); } }
        public static Color Lime { get { return Color.FromRGBA(0x00, 0xFF, 0x00, 0xFF); } }
        public static Color Linen { get { return Color.FromRGBA(0xFA, 0xF0, 0xE6, 0xFF); } }
        public static Color Yellow { get { return Color.FromRGBA(0xFF, 0xFF, 0x00, 0xFF); } }
        public static Color Orange { get { return Color.FromRGBA(0xFF, 0xA5, 0x00, 0xFF); } }
        public static Color Orchid { get { return Color.FromRGBA(0xDA, 0x70, 0xD6, 0xFF); } }
        public static Color Silver { get { return Color.FromRGBA(0xC0, 0xC0, 0xC0, 0xFF); } }
        public static Color SkyBlue { get { return Color.FromRGBA(0x87, 0xCE, 0xEB, 0xFF); } }
        public static Color SlateBlue { get { return Color.FromRGBA(0x6A, 0x5A, 0xCD, 0xFF); } }
        public static Color SlateGray { get { return Color.FromRGBA(0x70, 0x80, 0x90, 0xFF); } }
        public static Color Snow { get { return Color.FromRGBA(0xFF, 0xFA, 0xFA, 0xFF); } }
        public static Color SpringGreen { get { return Color.FromRGBA(0x00, 0xFF, 0x7F, 0xFF); } }
        public static Color SteelBlue { get { return Color.FromRGBA(0x46, 0x82, 0xB4, 0xFF); } }
        public static Color Tan { get { return Color.FromRGBA(0xD2, 0xB4, 0x8C, 0xFF); } }
        public static Color Teal { get { return Color.FromRGBA(0x00, 0x80, 0x80, 0xFF); } }
        public static Color Thistle { get { return Color.FromRGBA(0xD8, 0xBF, 0xD8, 0xFF); } }
        public static Color Tomato { get { return Color.FromRGBA(0xFF, 0x63, 0x47, 0xFF); } }
        public static Color Transparent { get { return Color.FromRGBA(0x00, 0x00, 0x00, 0x00); } }
        public static Color Turquoise { get { return Color.FromRGBA(0x40, 0xE0, 0xD0, 0xFF); } }
        public static Color Violet { get { return Color.FromRGBA(0xEE, 0x82, 0xEE, 0xFF); } }
        public static Color Wheat { get { return Color.FromRGBA(0xF5, 0xDE, 0xB3, 0xFF); } }
        public static Color White { get { return Color.FromRGBA(0xFF, 0xFF, 0xFF, 0xFF); } }
        public static Color WhiteSmoke { get { return Color.FromRGBA(0xF5, 0xF5, 0xF5, 0xFF); } }
        public static Color Sienna { get { return Color.FromRGBA(0xA0, 0x52, 0x2D, 0xFF); } }
        public static Color OrangeRed { get { return Color.FromRGBA(0xFF, 0x45, 0x00, 0xFF); } }
        public static Color SeaShell { get { return Color.FromRGBA(0xFF, 0xF5, 0xEE, 0xFF); } }
        public static Color SandyBrown { get { return Color.FromRGBA(0xF4, 0xA4, 0x60, 0xFF); } }
        public static Color PaleGoldenrod { get { return Color.FromRGBA(0xEE, 0xE8, 0xAA, 0xFF); } }
        public static Color PaleGreen { get { return Color.FromRGBA(0x98, 0xFB, 0x98, 0xFF); } }
        public static Color PaleTurquoise { get { return Color.FromRGBA(0xAF, 0xEE, 0xEE, 0xFF); } }
        public static Color PaleVioletRed { get { return Color.FromRGBA(0xDB, 0x70, 0x93, 0xFF); } }
        public static Color PapayaWhip { get { return Color.FromRGBA(0xFF, 0xEF, 0xD5, 0xFF); } }
        public static Color PeachPuff { get { return Color.FromRGBA(0xFF, 0xDA, 0xB9, 0xFF); } }
        public static Color Peru { get { return Color.FromRGBA(0xCD, 0x85, 0x3F, 0xFF); } }
        public static Color Pink { get { return Color.FromRGBA(0xFF, 0xC0, 0xCB, 0xFF); } }
        public static Color Plum { get { return Color.FromRGBA(0xDD, 0xA0, 0xDD, 0xFF); } }
        public static Color PowderBlue { get { return Color.FromRGBA(0xB0, 0xE0, 0xE6, 0xFF); } }
        public static Color Purple { get { return Color.FromRGBA(0x80, 0x00, 0x80, 0xFF); } }
        public static Color RebeccaPurple { get { return Color.FromRGBA(0x66, 0x33, 0x99, 0xFF); } }
        public static Color Red { get { return Color.FromRGBA(0xFF, 0x00, 0x00, 0xFF); } }
        public static Color RosyBrown { get { return Color.FromRGBA(0xBC, 0x8F, 0x8F, 0xFF); } }
        public static Color RoyalBlue { get { return Color.FromRGBA(0x41, 0x69, 0xE1, 0xFF); } }
        public static Color SaddleBrown { get { return Color.FromRGBA(0x8B, 0x45, 0x13, 0xFF); } }
        public static Color Salmon { get { return Color.FromRGBA(0xFA, 0x80, 0x72, 0xFF); } }
        public static Color SeaGreen { get { return Color.FromRGBA(0x2E, 0x8B, 0x57, 0xFF); } }
        public static Color Khaki { get { return Color.FromRGBA(0xF0, 0xE6, 0x8C, 0xFF); } }
        public static Color Lavender { get { return Color.FromRGBA(0xE6, 0xE6, 0xFA, 0xFF); } }
        public static Color Cyan { get { return Color.FromRGBA(0x00, 0xFF, 0xFF, 0xFF); } }
        public static Color DarkMagenta { get { return Color.FromRGBA(0x8B, 0x00, 0x8B, 0xFF); } }
        public static Color DarkKhaki { get { return Color.FromRGBA(0xBD, 0xB7, 0x6B, 0xFF); } }
        public static Color DarkGreen { get { return Color.FromRGBA(0x00, 0x64, 0x00, 0xFF); } }
        public static Color DarkGray { get { return Color.FromRGBA(0xA9, 0xA9, 0xA9, 0xFF); } }
        public static Color DarkGoldenrod { get { return Color.FromRGBA(0xB8, 0x86, 0x0B, 0xFF); } }
        public static Color DarkCyan { get { return Color.FromRGBA(0x00, 0x8B, 0x8B, 0xFF); } }
        public static Color DarkBlue { get { return Color.FromRGBA(0x00, 0x00, 0x8B, 0xFF); } }
        public static Color Ivory { get { return Color.FromRGBA(0xFF, 0xFF, 0xF0, 0xFF); } }
        public static Color Crimson { get { return Color.FromRGBA(0xDC, 0x14, 0x3C, 0xFF); } }
        public static Color Cornsilk { get { return Color.FromRGBA(0xFF, 0xF8, 0xDC, 0xFF); } }
        public static Color CornflowerBlue { get { return Color.FromRGBA(0x64, 0x95, 0xED, 0xFF); } }
        public static Color Coral { get { return Color.FromRGBA(0xFF, 0x7F, 0x50, 0xFF); } }
        public static Color Chocolate { get { return Color.FromRGBA(0xD2, 0x69, 0x1E, 0xFF); } }
        public static Color DarkOliveGreen { get { return Color.FromRGBA(0x55, 0x6B, 0x2F, 0xFF); } }
        public static Color Chartreuse { get { return Color.FromRGBA(0x7F, 0xFF, 0x00, 0xFF); } }
        public static Color BurlyWood { get { return Color.FromRGBA(0xDE, 0xB8, 0x87, 0xFF); } }
        public static Color Brown { get { return Color.FromRGBA(0xA5, 0x2A, 0x2A, 0xFF); } }
        public static Color BlueViolet { get { return Color.FromRGBA(0x8A, 0x2B, 0xE2, 0xFF); } }
        public static Color Blue { get { return Color.FromRGBA(0x00, 0x00, 0xFF, 0xFF); } }
        public static Color BlanchedAlmond { get { return Color.FromRGBA(0xFF, 0xEB, 0xCD, 0xFF); } }
        public static Color Black { get { return Color.FromRGBA(0x00, 0x00, 0x00, 0xFF); } }
        public static Color Bisque { get { return Color.FromRGBA(0xFF, 0xE4, 0xC4, 0xFF); } }
        public static Color Beige { get { return Color.FromRGBA(0xF5, 0xF5, 0xDC, 0xFF); } }
        public static Color Azure { get { return Color.FromRGBA(0xF0, 0xFF, 0xFF, 0xFF); } }
        public static Color Aquamarine { get { return Color.FromRGBA(0x7F, 0xFF, 0xD4, 0xFF); } }
        public static Color Aqua { get { return Color.FromRGBA(0x00, 0xFF, 0xFF, 0xFF); } }
        public static Color AntiqueWhite { get { return Color.FromRGBA(0xFA, 0xEB, 0xD7, 0xFF); } }
        public static Color AliceBlue { get { return Color.FromRGBA(0xF0, 0xF8, 0xFF, 0xFF); } }
        public static Color CadetBlue { get { return Color.FromRGBA(0x5F, 0x9E, 0xA0, 0xFF); } }
        public static Color DarkOrange { get { return Color.FromRGBA(0xFF, 0x8C, 0x00, 0xFF); } }
        public static Color YellowGreen { get { return Color.FromRGBA(0x9A, 0xCD, 0x32, 0xFF); } }
        public static Color DarkRed { get { return Color.FromRGBA(0x8B, 0x00, 0x00, 0xFF); } }
        public static Color Indigo { get { return Color.FromRGBA(0x4B, 0x00, 0x82, 0xFF); } }
        public static Color IndianRed { get { return Color.FromRGBA(0xCD, 0x5C, 0x5C, 0xFF); } }
        public static Color DarkOrchid { get { return Color.FromRGBA(0x99, 0x32, 0xCC, 0xFF); } }
        public static Color Honeydew { get { return Color.FromRGBA(0xF0, 0xFF, 0xF0, 0xFF); } }
        public static Color GreenYellow { get { return Color.FromRGBA(0xAD, 0xFF, 0x2F, 0xFF); } }
        public static Color Green { get { return Color.FromRGBA(0x00, 0x80, 0x00, 0xFF); } }
        public static Color Gray { get { return Color.FromRGBA(0x80, 0x80, 0x80, 0xFF); } }
        public static Color Goldenrod { get { return Color.FromRGBA(0xDA, 0xA5, 0x20, 0xFF); } }
        public static Color Gold { get { return Color.FromRGBA(0xFF, 0xD7, 0x00, 0xFF); } }
        public static Color GhostWhite { get { return Color.FromRGBA(0xF8, 0xF8, 0xFF, 0xFF); } }
        public static Color Gainsboro { get { return Color.FromRGBA(0xDC, 0xDC, 0xDC, 0xFF); } }
        public static Color Fuchsia { get { return Color.FromRGBA(0xFF, 0x00, 0xFF, 0xFF); } }
        public static Color ForestGreen { get { return Color.FromRGBA(0x22, 0x8B, 0x22, 0xFF); } }
        public static Color HotPink { get { return Color.FromRGBA(0xFF, 0x69, 0xB4, 0xFF); } }
        public static Color Firebrick { get { return Color.FromRGBA(0xB2, 0x22, 0x22, 0xFF); } }
        public static Color FloralWhite { get { return Color.FromRGBA(0xFF, 0xFA, 0xF0, 0xFF); } }
        public static Color DodgerBlue { get { return Color.FromRGBA(0x1E, 0x90, 0xFF, 0xFF); } }
        public static Color DimGray { get { return Color.FromRGBA(0x69, 0x69, 0x69, 0xFF); } }
        public static Color DeepSkyBlue { get { return Color.FromRGBA(0x00, 0xBF, 0xFF, 0xFF); } }
        public static Color DeepPink { get { return Color.FromRGBA(0xFF, 0x14, 0x93, 0xFF); } }
        public static Color DarkViolet { get { return Color.FromRGBA(0x94, 0x00, 0xD3, 0xFF); } }
        public static Color DarkTurquoise { get { return Color.FromRGBA(0x00, 0xCE, 0xD1, 0xFF); } }
        public static Color DarkSlateGray { get { return Color.FromRGBA(0x2F, 0x4F, 0x4F, 0xFF); } }
        public static Color DarkSlateBlue { get { return Color.FromRGBA(0x48, 0x3D, 0x8B, 0xFF); } }
        public static Color DarkSeaGreen { get { return Color.FromRGBA(0x8F, 0xBC, 0x8B, 0xFF); } }
        public static Color DarkSalmon { get { return Color.FromRGBA(0xE9, 0x96, 0x7A, 0xFF); } }
    }
}
